# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

permissions:
  deployments: write
  contents: write
  statuses: write
  actions: write
  checks: read
  pull-requests: write
  issues: write
  repository-projects: write

jobs:
  java-build:
    uses: ./.github/workflows/maven-build.yml

  java-test:
    name: Java-Maven
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitActions
        uses: actions/checkout@v3

      - name: Test with Maven
        run: mvn -B test --file pom.xml

  bump-version:
    name: Bump-Maven
    needs:
      - java-build
      - java-test
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.bump.outputs.version }}
    steps:
      - name: Checkout GitActions
        uses: actions/checkout@v3

      - name: Bump Version
        id: bump
        uses: nnichols/maven-version-bump-action@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Print Version
        run: "echo 'New Version: ${{steps.bump.outputs.version}}'"

      - name: Upload artifact java
        uses: actions/upload-artifact@v2
        with:
          name: java-target
          path: |
            target/**/*
            Dockerfile

  docker-publish:
    name: Build & Push Docker Image
    needs:
      - bump-version
    runs-on: ubuntu-latest
    steps:
      - name: Baixar arquivo target
        uses: actions/download-artifact@v2
        with:
          name: java-target

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: relrypesan/learning-gitactions-app-java:${{ needs.bump-version.outputs.version }}
