
name: Java Build

on:
  workflow_call:

jobs:
  java-build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Waiting 10 seconds..."
          sleep 10
          echo "Hello World"

#      - name: Checkout GitActions
#        uses: actions/checkout@v3
#
#      - name: Set up JDK 11
#        uses: actions/setup-java@v3
#        with:
#          java-version: '11'
#          distribution: 'temurin'
#          cache: maven
#
#      - name: Build with Maven
#        run: mvn -B -DskipTests=true package --file pom.xml
#
#      - name: Upload artifact java
#        uses: actions/upload-artifact@v2
#        with:
#          name: java-target
#          path: |
#            target/**/*
#            Dockerfile
